baseURL = 'http://localhost:1313'
languageCode = 'en-gb'
title = 'garrynet 2.0'

theme = 'terminal'
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

  [params]
  contentTypeName = "posts"
  showMenuItems = 4
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  # readingTime = true # default
  # TocTitle = "Table of Contents" # default

[languages]
  [languages.en]
    languageName = "English"
    title = "garrynet 2.0"

    [languages.en.params]
      subtitle = "always evolving."
      owner = "Garry"
      # keywords = ""
      # copyright = ""
      menuMore = "more"
      readMore = "read post"
      readOtherPosts = "read other posts"
      newerPosts = "newer posts"
      olderPosts = "older posts"
      missingContentMessage = "page not found..."
      missingBackButtonLabel = "back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "garrynet 2.0"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "about"
          url = "/about"

        [[languages.en.menu.main]]
          identifier = "contact"
          name = "contact"
          url = "/contact"

        [[languages.en.menu.main]]
          identifier = "resume"
          name = "resume"
          url = "/resume"

        [[languages.en.menu.main]]
          identifier = "projects"
          name = "projects"
          url = "/projects"